/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package warproject;

/**
 *
 * @author 13221098774
 */
public class TelaDeJogo extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaDeJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telaInteira = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        logConsole = new javax.swing.JTextPane();
        console = new javax.swing.JLabel();
        painelOpcoes = new javax.swing.JTabbedPane();
        distribuir = new javax.swing.JPanel();
        labelPossui = new javax.swing.JLabel();
        qntExercitos = new javax.swing.JTextField();
        labelSoldados = new javax.swing.JLabel();
        Continuar = new javax.swing.JButton();
        reverter = new javax.swing.JButton();
        atacar = new javax.swing.JPanel();
        lPais = new javax.swing.JLabel();
        x = new javax.swing.JLabel();
        paisDefesa = new javax.swing.JTextField();
        paisAtaque = new javax.swing.JTextField();
        dadoUmAtaque = new javax.swing.JTextField();
        dadoUmDefesa = new javax.swing.JTextField();
        dadpDoisDefesa = new javax.swing.JTextField();
        dadoTresDefesa = new javax.swing.JTextField();
        dadoDoisAtaque = new javax.swing.JTextField();
        dadoTresAtaque = new javax.swing.JTextField();
        btnAtacar = new javax.swing.JButton();
        btnPassarAtaque = new javax.swing.JButton();
        movimentar = new javax.swing.JPanel();
        lbMovimentacao = new javax.swing.JLabel();
        passarMovimentacao = new javax.swing.JButton();
        lbPais = new javax.swing.JLabel();
        paisDe = new javax.swing.JTextField();
        paisPara = new javax.swing.JTextField();
        lbPara = new javax.swing.JLabel();
        numEx = new javax.swing.JLabel();
        qtdExercitos = new javax.swing.JFormattedTextField();
        enviaExercitos = new javax.swing.JButton();
        defender = new javax.swing.JPanel();
        dadoTresAtaqueD = new javax.swing.JTextField();
        paisDefesaD = new javax.swing.JTextField();
        dadoUmAtaqueD = new javax.swing.JTextField();
        xD = new javax.swing.JLabel();
        lPaisD = new javax.swing.JLabel();
        paisAtaqueD = new javax.swing.JTextField();
        btnDefenderD = new javax.swing.JButton();
        dadoTresDefesaD = new javax.swing.JTextField();
        dadoDoisAtaqueD = new javax.swing.JTextField();
        dadpDoisDefesaD = new javax.swing.JTextField();
        dadoUmDefesa1 = new javax.swing.JTextField();
        cartas = new javax.swing.JPanel();
        cartaObjetivo = new javax.swing.JLabel();
        cartaUm = new javax.swing.JLabel();
        cartaDois = new javax.swing.JLabel();
        cartaTres = new javax.swing.JLabel();
        cartaQuatro = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telaInteira.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setViewportView(logConsole);

        console.setText("Console");

        labelPossui.setText("Você possui:");

        qntExercitos.setText("0");
        qntExercitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qntExercitosActionPerformed(evt);
            }
        });

        labelSoldados.setText("soldados para distribuir.");

        Continuar.setText("Continuar");

        reverter.setText("Reverter");

        javax.swing.GroupLayout distribuirLayout = new javax.swing.GroupLayout(distribuir);
        distribuir.setLayout(distribuirLayout);
        distribuirLayout.setHorizontalGroup(
            distribuirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distribuirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(distribuirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(distribuirLayout.createSequentialGroup()
                        .addComponent(labelPossui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qntExercitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelSoldados)
                        .addGap(0, 191, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, distribuirLayout.createSequentialGroup()
                        .addComponent(reverter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Continuar)))
                .addContainerGap())
        );
        distribuirLayout.setVerticalGroup(
            distribuirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(distribuirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(distribuirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPossui)
                    .addComponent(qntExercitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSoldados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(distribuirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Continuar)
                    .addComponent(reverter))
                .addContainerGap())
        );

        painelOpcoes.addTab("Distribuir", distribuir);

        lPais.setText("Pais:");

        x.setText("X");

        paisDefesa.setText("Aegyptus");

        paisAtaque.setText("Cyrenaica");
        paisAtaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisAtaqueActionPerformed(evt);
            }
        });

        dadoUmAtaque.setText("0");

        dadoUmDefesa.setText("0");
        dadoUmDefesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoUmDefesaActionPerformed(evt);
            }
        });

        dadpDoisDefesa.setText("0");

        dadoTresDefesa.setText("0");

        dadoDoisAtaque.setText("0");

        dadoTresAtaque.setText("0");

        btnAtacar.setText("Atacar");

        btnPassarAtaque.setText("Passar");

        javax.swing.GroupLayout atacarLayout = new javax.swing.GroupLayout(atacar);
        atacar.setLayout(atacarLayout);
        atacarLayout.setHorizontalGroup(
            atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atacarLayout.createSequentialGroup()
                .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atacarLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dadoUmAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(atacarLayout.createSequentialGroup()
                                .addComponent(lPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paisAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dadoDoisAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dadoTresAtaque, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(x)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(atacarLayout.createSequentialGroup()
                        .addComponent(dadoTresDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtacar))
                    .addGroup(atacarLayout.createSequentialGroup()
                        .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paisDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dadoUmDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 86, Short.MAX_VALUE))
                    .addGroup(atacarLayout.createSequentialGroup()
                        .addComponent(dadpDoisDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPassarAtaque)))
                .addContainerGap())
        );
        atacarLayout.setVerticalGroup(
            atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atacarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPais)
                    .addComponent(x)
                    .addComponent(paisDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadoUmAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadoUmDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadpDoisDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadoDoisAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPassarAtaque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(atacarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadoTresDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadoTresAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtacar))
                .addContainerGap())
        );

        painelOpcoes.addTab("Atacar", atacar);

        lbMovimentacao.setText("Movimentação");

        passarMovimentacao.setText("Passar");

        lbPais.setText("Do pais");

        paisDe.setText("Africa");

        paisPara.setText("Sicilia");
        paisPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisParaActionPerformed(evt);
            }
        });

        lbPara.setText("para");

        numEx.setText("Numero de exércitos:");

        qtdExercitos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        qtdExercitos.setText("0");

        enviaExercitos.setText("Enviar");

        javax.swing.GroupLayout movimentarLayout = new javax.swing.GroupLayout(movimentar);
        movimentar.setLayout(movimentarLayout);
        movimentarLayout.setHorizontalGroup(
            movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movimentarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(passarMovimentacao))
                    .addGroup(movimentarLayout.createSequentialGroup()
                        .addGroup(movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMovimentacao)
                            .addGroup(movimentarLayout.createSequentialGroup()
                                .addGroup(movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, movimentarLayout.createSequentialGroup()
                                        .addComponent(numEx)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(qtdExercitos))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, movimentarLayout.createSequentialGroup()
                                        .addComponent(lbPais)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(paisDe, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbPara)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paisPara, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enviaExercitos))))
                        .addGap(0, 147, Short.MAX_VALUE)))
                .addContainerGap())
        );
        movimentarLayout.setVerticalGroup(
            movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movimentarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMovimentacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPais)
                    .addComponent(paisDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPara))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(movimentarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numEx)
                    .addComponent(qtdExercitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviaExercitos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(passarMovimentacao)
                .addContainerGap())
        );

        painelOpcoes.addTab("Movimentar", movimentar);

        dadoTresAtaqueD.setText("0");

        paisDefesaD.setText("Cappadocia");

        dadoUmAtaqueD.setText("0");

        xD.setText("X");

        lPaisD.setText("Pais:");

        paisAtaqueD.setText("Asia");

        btnDefenderD.setText("Defender");

        dadoTresDefesaD.setText("0");

        dadoDoisAtaqueD.setText("0");

        dadpDoisDefesaD.setText("0");

        dadoUmDefesa1.setText("0");
        dadoUmDefesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dadoUmDefesa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defenderLayout = new javax.swing.GroupLayout(defender);
        defender.setLayout(defenderLayout);
        defenderLayout.setHorizontalGroup(
            defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defenderLayout.createSequentialGroup()
                .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defenderLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dadoUmAtaqueD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(defenderLayout.createSequentialGroup()
                                .addComponent(lPaisD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paisAtaqueD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dadoDoisAtaqueD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dadoTresAtaqueD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defenderLayout.createSequentialGroup()
                        .addComponent(dadoTresDefesaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDefenderD))
                    .addGroup(defenderLayout.createSequentialGroup()
                        .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paisDefesaD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dadoUmDefesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dadpDoisDefesaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 86, Short.MAX_VALUE)))
                .addContainerGap())
        );
        defenderLayout.setVerticalGroup(
            defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defenderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPaisD)
                    .addComponent(xD)
                    .addComponent(paisDefesaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisAtaqueD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadoUmAtaqueD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadoUmDefesa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadpDoisDefesaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadoDoisAtaqueD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(defenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dadoTresDefesaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dadoTresAtaqueD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefenderD))
                .addContainerGap())
        );

        painelOpcoes.addTab("Defender", defender);

        cartaObjetivo.setText("Carta Objetivo");

        cartaUm.setText("Carta1");

        cartaDois.setText("Carta2");

        cartaTres.setText("Carta3");

        cartaQuatro.setText("Carta4");

        jLabel6.setText("Carta5");

        jButton1.setText("Trocar");

        javax.swing.GroupLayout cartasLayout = new javax.swing.GroupLayout(cartas);
        cartas.setLayout(cartasLayout);
        cartasLayout.setHorizontalGroup(
            cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cartasLayout.createSequentialGroup()
                        .addGroup(cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartaTres)
                            .addComponent(cartaObjetivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addGroup(cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartaQuatro)
                            .addComponent(cartaUm))
                        .addGap(108, 108, 108)
                        .addGroup(cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cartaDois, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cartasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        cartasLayout.setVerticalGroup(
            cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cartaObjetivo)
                    .addComponent(cartaUm)
                    .addComponent(cartaDois))
                .addGap(46, 46, 46)
                .addGroup(cartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cartaQuatro)
                    .addComponent(cartaTres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        painelOpcoes.addTab("Cartas", cartas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(console)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(console)
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        telaInteira.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1130, 210));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel1.setName("btnLugdunensis"); // NOI18N
        telaInteira.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel3.setName("btnGermaniaSuperior"); // NOI18N
        telaInteira.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel4.setName("btnAquitania"); // NOI18N
        telaInteira.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel5.setName("btnTarraconensis"); // NOI18N
        telaInteira.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel7.setName("btnLusitania"); // NOI18N
        telaInteira.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel8.setName("btnGermaniaInferior"); // NOI18N
        telaInteira.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel9.setName("btnRaetia"); // NOI18N
        telaInteira.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel10.setName("btnBaetica"); // NOI18N
        telaInteira.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel11.setName("btnNarbonensis"); // NOI18N
        telaInteira.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel12.setName("btnBritania"); // NOI18N
        telaInteira.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel13.setName("btnThracia"); // NOI18N
        telaInteira.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 210, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel14.setName("btnItalia"); // NOI18N
        telaInteira.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel15.setName("btnCorsica"); // NOI18N
        telaInteira.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel16.setName("btnSicilia"); // NOI18N
        telaInteira.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel17.setName("btnMauritania"); // NOI18N
        telaInteira.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel18.setName("btnNumidia"); // NOI18N
        telaInteira.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel19.setName("btnAfrica"); // NOI18N
        telaInteira.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel20.setName("btnCyrenaica"); // NOI18N
        telaInteira.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel21.setName("btnAegyptus"); // NOI18N
        telaInteira.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel22.setName("btnCreta"); // NOI18N
        telaInteira.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel23.setName("btnAchaca"); // NOI18N
        telaInteira.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel24.setName("btnMacedonia"); // NOI18N
        telaInteira.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel25.setName("btnIllyricum"); // NOI18N
        telaInteira.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 153, 153));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setName("btnDacia"); // NOI18N
        telaInteira.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 70, 70));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel26.setName("btnCappadocia"); // NOI18N
        telaInteira.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, -1, -1));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel28.setToolTipText("");
        jLabel28.setName("btnTaurica"); // NOI18N
        telaInteira.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel29.setName("btnBithynia"); // NOI18N
        telaInteira.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel30.setName("btnGalatia"); // NOI18N
        telaInteira.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel31.setName("btnAsia"); // NOI18N
        telaInteira.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel32.setName("btnCyprus"); // NOI18N
        telaInteira.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 300, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel33.setName("btnAssyria"); // NOI18N
        telaInteira.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 240, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel34.setName("btnLycia"); // NOI18N
        telaInteira.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel35.setName("btnSyria"); // NOI18N
        telaInteira.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 280, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel36.setName("btnArabiaPetrae"); // NOI18N
        telaInteira.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel37.setName("btnJudaca"); // NOI18N
        telaInteira.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 340, -1, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel38.setName("btnMesopotamia"); // NOI18N
        telaInteira.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel39.setName("btnPonfus"); // NOI18N
        telaInteira.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 180, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel40.setName("btnArmenia"); // NOI18N
        telaInteira.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 210, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel41.setName("btnPandomia"); // NOI18N
        telaInteira.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel42.setName("btnMoesia"); // NOI18N
        telaInteira.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel43.setName("btnSardina"); // NOI18N
        telaInteira.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/botao-semdono.png"))); // NOI18N
        jLabel44.setName("btnBelgica"); // NOI18N
        telaInteira.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setText("1");
        jButton2.setActionCommand("1");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(black);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        telaInteira.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 20, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/Mapa.png"))); // NOI18N
        telaInteira.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(telaInteira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(telaInteira, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qntExercitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qntExercitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qntExercitosActionPerformed

    private void dadoUmDefesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoUmDefesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dadoUmDefesaActionPerformed

    private void paisParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisParaActionPerformed

    private void dadoUmDefesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dadoUmDefesa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dadoUmDefesa1ActionPerformed

    private void paisAtaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisAtaqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisAtaqueActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeJogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeJogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continuar;
    private javax.swing.JPanel atacar;
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnDefenderD;
    private javax.swing.JButton btnPassarAtaque;
    private javax.swing.JLabel cartaDois;
    private javax.swing.JLabel cartaObjetivo;
    private javax.swing.JLabel cartaQuatro;
    private javax.swing.JLabel cartaTres;
    private javax.swing.JLabel cartaUm;
    private javax.swing.JPanel cartas;
    private javax.swing.JLabel console;
    private javax.swing.JTextField dadoDoisAtaque;
    private javax.swing.JTextField dadoDoisAtaqueD;
    private javax.swing.JTextField dadoTresAtaque;
    private javax.swing.JTextField dadoTresAtaqueD;
    private javax.swing.JTextField dadoTresDefesa;
    private javax.swing.JTextField dadoTresDefesaD;
    private javax.swing.JTextField dadoUmAtaque;
    private javax.swing.JTextField dadoUmAtaqueD;
    private javax.swing.JTextField dadoUmDefesa;
    private javax.swing.JTextField dadoUmDefesa1;
    private javax.swing.JTextField dadpDoisDefesa;
    private javax.swing.JTextField dadpDoisDefesaD;
    private javax.swing.JPanel defender;
    private javax.swing.JPanel distribuir;
    private javax.swing.JButton enviaExercitos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lPais;
    private javax.swing.JLabel lPaisD;
    private javax.swing.JLabel labelPossui;
    private javax.swing.JLabel labelSoldados;
    private javax.swing.JLabel lbMovimentacao;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbPara;
    private javax.swing.JTextPane logConsole;
    private javax.swing.JPanel movimentar;
    private javax.swing.JLabel numEx;
    private javax.swing.JTabbedPane painelOpcoes;
    private javax.swing.JTextField paisAtaque;
    private javax.swing.JTextField paisAtaqueD;
    private javax.swing.JTextField paisDe;
    private javax.swing.JTextField paisDefesa;
    private javax.swing.JTextField paisDefesaD;
    private javax.swing.JTextField paisPara;
    private javax.swing.JButton passarMovimentacao;
    private javax.swing.JTextField qntExercitos;
    private javax.swing.JFormattedTextField qtdExercitos;
    private javax.swing.JButton reverter;
    private javax.swing.JPanel telaInteira;
    private javax.swing.JLabel x;
    private javax.swing.JLabel xD;
    // End of variables declaration//GEN-END:variables
}
