/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warproject;

import controller.Gerenciador;
import javax.swing.JOptionPane;

/**
 *
 * @author 13221098774
 */
public class TelaInicial extends javax.swing.JFrame {

    int Maquina = 0;
    int Player = 1;

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoApelido1 = new javax.swing.JTextField();
        iniciarJogo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        apelido1 = new javax.swing.JLabel();
        apelido2 = new javax.swing.JLabel();
        cbEscolhaCor1 = new javax.swing.JComboBox();
        apelido3 = new javax.swing.JLabel();
        apelido4 = new javax.swing.JLabel();
        apelido6 = new javax.swing.JLabel();
        textoApelido2 = new javax.swing.JTextField();
        apelido7 = new javax.swing.JLabel();
        cbEscolhaCor2 = new javax.swing.JComboBox();
        apelido8 = new javax.swing.JLabel();
        apelido10 = new javax.swing.JLabel();
        textoApelido3 = new javax.swing.JTextField();
        apelido11 = new javax.swing.JLabel();
        cbEscolhaCor3 = new javax.swing.JComboBox();
        apelido12 = new javax.swing.JLabel();
        apelido14 = new javax.swing.JLabel();
        textoApelido4 = new javax.swing.JTextField();
        apelido15 = new javax.swing.JLabel();
        cbEscolhaCor4 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoApelido1.setText("Jogador 1");
        textoApelido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApelido1ActionPerformed(evt);
            }
        });
        jPanel1.add(textoApelido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 280, -1));

        iniciarJogo.setBackground(new java.awt.Color(102, 0, 0));
        iniciarJogo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        iniciarJogo.setForeground(new java.awt.Color(255, 255, 255));
        iniciarJogo.setText("Entrar");
        iniciarJogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        iniciarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarJogoActionPerformed(evt);
            }
        });
        jPanel1.add(iniciarJogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/fundo-gladiadores.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        apelido1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido1.setForeground(new java.awt.Color(102, 102, 102));
        apelido1.setText("Jogador 1:");
        jPanel1.add(apelido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        apelido2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido2.setText("cor:");
        jPanel1.add(apelido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        cbEscolhaCor1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Verde", "Azul", "Preto" }));
        cbEscolhaCor1.setEnabled(false);
        cbEscolhaCor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaCor1ActionPerformed(evt);
            }
        });
        jPanel1.add(cbEscolhaCor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        apelido3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido3.setText("Apelido:");
        jPanel1.add(apelido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        apelido4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido4.setForeground(new java.awt.Color(102, 102, 102));
        apelido4.setText("Jogador 2:");
        jPanel1.add(apelido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        apelido6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido6.setText("Apelido:");
        jPanel1.add(apelido6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        textoApelido2.setText("Jogador 2");
        textoApelido2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApelido2ActionPerformed(evt);
            }
        });
        jPanel1.add(textoApelido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 280, -1));

        apelido7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido7.setText("cor:");
        jPanel1.add(apelido7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        cbEscolhaCor2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Verde", "Azul", "Preto" }));
        cbEscolhaCor2.setSelectedIndex(1);
        cbEscolhaCor2.setEnabled(false);
        cbEscolhaCor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaCor2ActionPerformed(evt);
            }
        });
        jPanel1.add(cbEscolhaCor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        apelido8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido8.setForeground(new java.awt.Color(102, 102, 102));
        apelido8.setText("Jogador 3:");
        jPanel1.add(apelido8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        apelido10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido10.setText("Apelido:");
        jPanel1.add(apelido10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        textoApelido3.setText("Jogador 3");
        textoApelido3.setMaximumSize(null);
        textoApelido3.setMinimumSize(null);
        textoApelido3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApelido3ActionPerformed(evt);
            }
        });
        jPanel1.add(textoApelido3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 280, -1));

        apelido11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido11.setText("cor:");
        jPanel1.add(apelido11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        cbEscolhaCor3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Verde", "Azul", "Preto" }));
        cbEscolhaCor3.setSelectedIndex(2);
        cbEscolhaCor3.setEnabled(false);
        cbEscolhaCor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaCor3ActionPerformed(evt);
            }
        });
        jPanel1.add(cbEscolhaCor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, -1, -1));

        apelido12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido12.setForeground(new java.awt.Color(102, 102, 102));
        apelido12.setText("Jogador 4:");
        jPanel1.add(apelido12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        apelido14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido14.setText("Apelido:");
        jPanel1.add(apelido14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        textoApelido4.setText("Jogador 4");
        textoApelido4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoApelido4ActionPerformed(evt);
            }
        });
        jPanel1.add(textoApelido4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 280, -1));

        apelido15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        apelido15.setText("cor:");
        jPanel1.add(apelido15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        cbEscolhaCor4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vermelho", "Verde", "Azul", "Preto" }));
        cbEscolhaCor4.setSelectedIndex(3);
        cbEscolhaCor4.setEnabled(false);
        cbEscolhaCor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEscolhaCor4ActionPerformed(evt);
            }
        });
        jPanel1.add(cbEscolhaCor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoApelido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApelido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApelido1ActionPerformed

    private void iniciarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarJogoActionPerformed
        if ((textoApelido1.getText().isEmpty()) || (textoApelido2.getText().isEmpty()) || (textoApelido3.getText().isEmpty()) || (textoApelido4.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Os nomes nao podem ficar vazios!");
        } else {
            String escolhaCor1 = cbEscolhaCor1.getSelectedIndex() + "";
            String escolhaCor2 = cbEscolhaCor2.getSelectedIndex() + "";
            String escolhaCor3 = cbEscolhaCor3.getSelectedIndex() + "";
            String escolhaCor4 = cbEscolhaCor4.getSelectedIndex() + "";

            String apelido1 = textoApelido1.getText();
            String apelido2 = textoApelido2.getText();
            String apelido3 = textoApelido3.getText();
            String apelido4 = textoApelido4.getText();

            String[][] paramentros = {
                {apelido1, escolhaCor1},
                {apelido2, escolhaCor2},
                {apelido3, escolhaCor3},
                {apelido4, escolhaCor4}
            };
            Gerenciador gerenciador = Gerenciador.getInstance(paramentros);
            TelaOpcoes tela = new TelaOpcoes();
            tela.setVisible(true);
            tela.setLocationRelativeTo(null);
            dispose();
        }
    }//GEN-LAST:event_iniciarJogoActionPerformed

    private void textoApelido2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApelido2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApelido2ActionPerformed

    private void textoApelido3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApelido3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApelido3ActionPerformed

    private void textoApelido4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoApelido4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoApelido4ActionPerformed

    private void cbEscolhaCor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaCor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEscolhaCor4ActionPerformed

    private void cbEscolhaCor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaCor3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEscolhaCor3ActionPerformed

    private void cbEscolhaCor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaCor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEscolhaCor2ActionPerformed

    private void cbEscolhaCor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEscolhaCor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEscolhaCor1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apelido1;
    private javax.swing.JLabel apelido10;
    private javax.swing.JLabel apelido11;
    private javax.swing.JLabel apelido12;
    private javax.swing.JLabel apelido14;
    private javax.swing.JLabel apelido15;
    private javax.swing.JLabel apelido2;
    private javax.swing.JLabel apelido3;
    private javax.swing.JLabel apelido4;
    private javax.swing.JLabel apelido6;
    private javax.swing.JLabel apelido7;
    private javax.swing.JLabel apelido8;
    private javax.swing.JComboBox cbEscolhaCor1;
    private javax.swing.JComboBox cbEscolhaCor2;
    private javax.swing.JComboBox cbEscolhaCor3;
    private javax.swing.JComboBox cbEscolhaCor4;
    private javax.swing.JButton iniciarJogo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField textoApelido1;
    private javax.swing.JTextField textoApelido2;
    private javax.swing.JTextField textoApelido3;
    private javax.swing.JTextField textoApelido4;
    // End of variables declaration//GEN-END:variables
}
