/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package warproject;

/**
 *
 * @author Samsung
 */
public class TelaDeCartas extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeCartas
     */
    public TelaDeCartas(String tipo, String descricao, String tipoDescricao) {
        initComponents();
        tipoNome.setText(tipo);
        conteudo.setText(descricao);
        tipoConteudo.setText(tipoDescricao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipoNome = new javax.swing.JLabel();
        tipoConteudo = new javax.swing.JTextArea();
        conteudo = new javax.swing.JTextArea();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(167, 257));
        setModalExclusionType(null);
        setResizable(false);

        jPanel1.setLayout(null);

        tipoNome.setBackground(new java.awt.Color(255, 255, 255));
        tipoNome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tipoNome.setForeground(new java.awt.Color(255, 255, 255));
        tipoNome.setText("Território");
        jPanel1.add(tipoNome);
        tipoNome.setBounds(50, 0, 79, 30);

        tipoConteudo.setEditable(false);
        tipoConteudo.setColumns(20);
        tipoConteudo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tipoConteudo.setForeground(new java.awt.Color(255, 255, 255));
        tipoConteudo.setLineWrap(true);
        tipoConteudo.setRows(5);
        tipoConteudo.setText("TRIANGULO");
        tipoConteudo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        tipoConteudo.setEnabled(false);
        tipoConteudo.setOpaque(false);
        jPanel1.add(tipoConteudo);
        tipoConteudo.setBounds(50, 210, 80, 20);

        conteudo.setEditable(false);
        conteudo.setColumns(20);
        conteudo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        conteudo.setForeground(new java.awt.Color(255, 255, 255));
        conteudo.setLineWrap(true);
        conteudo.setRows(5);
        conteudo.setText("CONQUISTAR NA \nTOTALIDADE A\nAMERICA DO SUL\nA ASIA \nE MAIS UM CONTINENTE\nA SUA ESCOLHA.");
        conteudo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        conteudo.setEnabled(false);
        conteudo.setOpaque(false);
        jPanel1.add(conteudo);
        conteudo.setBounds(20, 40, 140, 150);

        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/warproject/carta.png"))); // NOI18N
        background.setMinimumSize(new java.awt.Dimension(175, 240));
        background.setName(""); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 175, 242);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextArea conteudo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea tipoConteudo;
    private javax.swing.JLabel tipoNome;
    // End of variables declaration//GEN-END:variables
}
